version: '3.9'

services:
  api:
    image: 954247117315.dkr.ecr.us-east-1.amazonaws.com/api:latest
    ports:
      - '8000:8000'
    env_file:
      - .env

    depends_on:
      - postgres
  indexer:
    image: 954247117315.dkr.ecr.us-east-1.amazonaws.com/indexer:latest
    env_file:
      - .env
    environment:
      - ALCHEMY_URL=$ALCHEMY_URL
      - INDEXING_STRATEGY='continuously'
      - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
      - FROM_BLOCK=$FROM_BLOCK
      - TO_BLOCK=$TO_BLOCK
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PG_PASSWORD
      - POSTGRES__DB=$PG_DB
      - POSTGRES_HOST=$PG_HOST
      - POSTGRES_PORT=$PG_PORT
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5432

volumes:
  db:
    driver: local
