version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: app/server/Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PYTHONPATH="/usr/app"

  doge_indexer:
    build:
      context: .
      dockerfile: app/indexers/Dockerfile
    environment:
      - PYTHONPATH="/usr/app"
      - ALCHEMY_URL="https://eth-mainnet.g.alchemy.com/v2/hTng6pRagvXdsPNQwfXZLgVr4_Np2p7G"
