version: '3.9'

services:
  api:
    image: 954247117315.dkr.ecr.us-east-1.amazonaws.com/api:latest
    ports:
      - '8000:8000'
    env_file:
      - .env

    links:
      - postgres

  indexer:
    image: 954247117315.dkr.ecr.us-east-1.amazonaws.com/indexer:latest
    env_file:
      - .env
    environment:
      - ALCHEMY_URL=$ALCHEMY_URL
      - INDEXING_STRATEGY=$INDEXING_STRATEGY
      - CONTRACT_ADDRESS=$CONTRACT_ADDRESS
      - FROM_BLOCK=$FROM_BLOCK
      - TO_BLOCK=$TO_BLOCK
    links:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      - PG_USER=$PG_USER
      - PG_PASSWORD=$PG_PASSWORD
      - PG_DB=$PG_DB
      - PG_HOST=$PG_HOST
      - PG_PORT=$PG_PORT
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5433

volumes:
  db:
    driver: local
