version: '3.10'

services:
  api:
    build:
      context: ./app/server
    command: python main.py
    volumes:
      - ./app/server:/app/server
    ports:
      - '8000:8000'
    restart: unless-stopped

  doge_indexer:
    build:
      context: ./app/indexers
    environment:
      - INDEXING_STRATEGY=continuously
    command: sh -c 'python main.py'
    volumes:
      - ./app/indexers:/app/indexers
    restart: unless-stopped
