version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: app/server/Dockerfile
    ports:
      - '8000:8000'
    links:
      - postgres

  doge_indexer:
    build:
      context: .
      dockerfile: app/indexers/Dockerfile
    environment:
      - ALCHEMY_URL=${ALCHEMY_URL}
      - INDEXING_STRATEGY=${INDEXING_STRATEGY}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - FROM_BLOCK=${FROM_BLOCK}
      - TO_BLOCK=${TO_BLOCK}
    links:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    command: -p 5433
volumes:
  db:
    driver: local
