version: '3.10'

services:
  api:
    build: ./app/server
    command: python main.py
    volumes:
      - ./app/server:/app
    ports:
      - '8000:8000'
    restart: unless-stopped

  doge_indexer:
    build: ./app/indexers
    environment:
      - INDEXING_STRATEGY=continuously
    command: sh -c 'python main.py'
    volumes:
      - ./app/indexers:/app
    restart: unless-stopped
